packages:
  - docs
  - examples/*
  - packages/*

catalog:
  '@antfu/eslint-config': ^5.2.1
  '@moeru/eslint-config': &std ^0.1.0-beta.9
  '@moeru/tsconfig': *std
  bumpp: ^10.2.3
  eslint: ^9.33.0
  pkgroll: ^2.15.3
  tsx: ^4.20.5
  typescript: ~5.8.3

catalogs:
  xsai:
    '@xsai/generate-text': &xsai ^0.4.0-beta.3
    '@xsai/shared-chat': *xsai
    '@xsai/stream-text': *xsai
