packages:
  - docs
  - examples/*
  - packages/*

catalog:
  '@antfu/eslint-config': ^5.2.1
  '@moeru/eslint-config': ^0.1.0-beta.8
  '@moeru/tsconfig': ^0.1.0-beta.8
  bumpp: ^10.2.3
  eslint: ^9.33.0
  pkgroll: ^2.15.3
  tsx: ^4.20.5
  typescript: ~5.8.3
